// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WwTool.Common.Context;

#nullable disable

namespace WwTool.Common.Context.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803081351_FullSpecificationMigration")]
    partial class FullSpecificationMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("WwTool.Common.Models.Entities.GachaImportBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FirstSourceOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSourceOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PoolType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCursor")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Uid");

                    b.ToTable("GachaImportBatches", (string)null);
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.GachaRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiPageIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuplicateOccurrenceIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("PoolType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseItemIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("SourceOccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StableFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("Uid", "PoolType", "SourceOccurredAtUtc");

                    b.HasIndex("Uid", "PoolType", "SourceOrder")
                        .IsUnique();

                    b.HasIndex("Uid", "PoolType", "StableFingerprint")
                        .IsUnique();

                    b.ToTable("GachaRecords", (string)null);
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.PlayerBaseInfo", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BasicBoxesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BirthDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthMon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoxesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EnergyRecoverTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Liveness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivenessMaxCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LivenessUnlock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxEnergy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStoreEnergy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhantomBoxesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoundBox")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreEnergy")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StoreEnergyRecoverTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeeklyInstCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorldLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uid");

                    b.ToTable("PlayerBaseInfos", (string)null);
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.PlayerBattlePass", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUnlock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekExp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekMaxExp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uid");

                    b.ToTable("PlayerBattlePasses", (string)null);
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.PlayerMotorData", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecorationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipSkinId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipSkinQuality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FramesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextExp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkinsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StickersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Uid");

                    b.ToTable("PlayerMotorData", (string)null);
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.PlayerMusicData", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<int>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uid", "AlbumId");

                    b.ToTable("PlayerMusicData", (string)null);
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.SyncState", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataKind")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCursor")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SourceUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Uid", "DataKind", "ScopeKey");

                    b.ToTable("SyncStates", (string)null);
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.UserAccount", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedOauthCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeadPhoto")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uid");

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.GachaImportBatch", b =>
                {
                    b.HasOne("WwTool.Common.Models.Entities.UserAccount", "UserAccount")
                        .WithMany("GachaImportBatches")
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.GachaRecord", b =>
                {
                    b.HasOne("WwTool.Common.Models.Entities.GachaImportBatch", "ImportBatch")
                        .WithMany("Records")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WwTool.Common.Models.Entities.UserAccount", "UserAccount")
                        .WithMany("GachaRecords")
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.PlayerBaseInfo", b =>
                {
                    b.HasOne("WwTool.Common.Models.Entities.UserAccount", "UserAccount")
                        .WithOne()
                        .HasForeignKey("WwTool.Common.Models.Entities.PlayerBaseInfo", "Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.PlayerBattlePass", b =>
                {
                    b.HasOne("WwTool.Common.Models.Entities.UserAccount", "UserAccount")
                        .WithOne()
                        .HasForeignKey("WwTool.Common.Models.Entities.PlayerBattlePass", "Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.PlayerMotorData", b =>
                {
                    b.HasOne("WwTool.Common.Models.Entities.UserAccount", "UserAccount")
                        .WithOne()
                        .HasForeignKey("WwTool.Common.Models.Entities.PlayerMotorData", "Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.PlayerMusicData", b =>
                {
                    b.HasOne("WwTool.Common.Models.Entities.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.SyncState", b =>
                {
                    b.HasOne("WwTool.Common.Models.Entities.UserAccount", "UserAccount")
                        .WithMany("SyncStates")
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.GachaImportBatch", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("WwTool.Common.Models.Entities.UserAccount", b =>
                {
                    b.Navigation("GachaImportBatches");

                    b.Navigation("GachaRecords");

                    b.Navigation("SyncStates");
                });
#pragma warning restore 612, 618
        }
    }
}
