// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WwTool.Common.Context;

#nullable disable

namespace WwTool.Common.Context.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622113232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("WwTool.Common.Models.GachaRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PoolType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Uid", "PoolType", "Time")
                        .IsDescending(false, false, true);

                    b.ToTable("GachaRecords");
                });

            modelBuilder.Entity("WwTool.Common.Models.PlayerBaseInfo", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BasicBoxesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BirthDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthMon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoxesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EnergyRecoverTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Liveness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivenessMaxCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LivenessUnlock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxEnergy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStoreEnergy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhantomBoxesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoundBox")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreEnergy")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StoreEnergyRecoverTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeeklyInstCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorldLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uid");

                    b.ToTable("PlayerBaseInfos");
                });

            modelBuilder.Entity("WwTool.Common.Models.PlayerBattlePass", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUnlock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekExp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekMaxExp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uid");

                    b.ToTable("PlayerBattlePasses");
                });

            modelBuilder.Entity("WwTool.Common.Models.PlayerMotorData", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecorationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipSkinId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipSkinQuality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FramesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextExp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkinsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StickersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Uid");

                    b.ToTable("PlayerMotorData");
                });

            modelBuilder.Entity("WwTool.Common.Models.PlayerMusicData", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<int>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uid", "AlbumId");

                    b.ToTable("PlayerMusicData");
                });

            modelBuilder.Entity("WwTool.Common.Models.UserAccount", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedOauthCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeadPhoto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uid");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("WwTool.Common.Models.GachaRecord", b =>
                {
                    b.HasOne("WwTool.Common.Models.UserAccount", "UserAccount")
                        .WithMany("GachaRecords")
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WwTool.Common.Models.PlayerBaseInfo", b =>
                {
                    b.HasOne("WwTool.Common.Models.UserAccount", "UserAccount")
                        .WithOne()
                        .HasForeignKey("WwTool.Common.Models.PlayerBaseInfo", "Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WwTool.Common.Models.PlayerBattlePass", b =>
                {
                    b.HasOne("WwTool.Common.Models.UserAccount", "UserAccount")
                        .WithOne()
                        .HasForeignKey("WwTool.Common.Models.PlayerBattlePass", "Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WwTool.Common.Models.PlayerMotorData", b =>
                {
                    b.HasOne("WwTool.Common.Models.UserAccount", "UserAccount")
                        .WithOne()
                        .HasForeignKey("WwTool.Common.Models.PlayerMotorData", "Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WwTool.Common.Models.PlayerMusicData", b =>
                {
                    b.HasOne("WwTool.Common.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("WwTool.Common.Models.UserAccount", b =>
                {
                    b.Navigation("GachaRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
